### ISSUE TITLE
Open in new window (upper case `A/P`) not working?

### ISSUE THREAD

**Issue by amanjitsk** [duetosymmetry/arXiv-keys#10]
I can't seem to open abstract/pdf in a new window with `A/P`. I can only use the lower case equivalent of these.
My firefox version is 118.0.

**Comment by duetosymmetry** [comment]
Hi Amanjit, I believe this is because Firefox treats these open-in-new-window actions as popups, and you have popups disabled on the arXiv. You should be able to allow popups just for arXiv:
* Navigate to an arXiv page
* Hit the padlock 🔒 in the address bar
* Click on the right arrow > next to Connection Secure
* Click on More Information
* Go to the Permissions tab
* Find pop-up windows in the list of permissions and enable them
Please let me know if this was not the issue!

**Comment by amanjitsk** [comment]
Thanks for the quick reply Professor! That was indeed the problem.
I always seem to forget about the popup blocking for firefox!
